# Generated by Django 5.2.5 on 2025-08-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='available_times',
            field=models.TextField(blank=True, default=''),
        ),
    ]
