# Generated by Django 5.2.5 on 2025-08-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.FileField(max_length=120, upload_to=''),
        ),
    ]
