# Generated by Django 5.2.5 on 2025-08-29 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
